name: "SSM Command Status Tracker"

description: "Send SSM Command with status tracking"

inputs:
  access-key-id:
    description: "AWS access key id"
    required: true
  secret-access-key:
    description: "AWS secret access key"
    required: true
  region:
    description: "Where EC2 instance is"
    required: true
  instance-id:
    description: "AWS EC2 Instance id"
    required: true
  command:
    description: "Bash command you want to execute"
    required: true
  working-directory:
    description: "Command execution location"
    required: true
  timeout:
    description: "Max time"
    default: 600000
  interval:
    description: "Time between each run"
    default: 10000
outputs:
  command-id:
    description: "Command id for ssm send-command"

runs:
  using: "node12"
  main: "dist/index.js"